name = "Superior FAF Experience"
uid = "SupFAF-17s2-0228-7g13-a21g61j2652i"
version = 1
description = "Best Mod Ever"
author = "Evildrew"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}